### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by zikezhang** [nhutdm/t430-hackintosh#1]
May I know WiFi and battery management is available in this repo?

Thank you !

**Comment by nhutdm** [comment]
Hi @zikezhang. This repo included toledaARPT kext for Atheros AR9285 AR5B95 and DSDT Patch for Power Management with latest BIOS version and 1600x900 resolution. I think you should follow guides available on [Tonymacx86.com](https://www.tonymacx86.com/) to patch your laptop's DSDT.

**Comment by zikezhang** [comment]
Thank you @nhutdm : yes, I found battery  management is working fined on my Hackintosh 👍 👍 👍 

Thank You !
