### ISSUE TITLE
hackintosh reboot automatically.

### ISSUE THREAD

**Issue by zikezhang** [nhutdm/t430-hackintosh#2]
Hello Nhutdm, 

I add the files in this repo to my hackintosh, but one problem is that my Thinkpad T430 reboot automatically after 20s I logged in. And my I know all the file in this directory t430-hackintosh/EFI/CLOVER/ ?

Thanks you !!

**Comment by nhutdm** [comment]
Hi @zikezhang. Could you give me your laptop specification?

**Comment by zikezhang** [comment]
Hi @nhutdm my laptop is thinkpad t430s. Do you need more details ?

**Comment by nhutdm** [comment]
How about the CPU @zikezhang?

**Comment by zikezhang** [comment]
Hi @nhutdm , my CUP is i5

**Comment by nhutdm** [comment]
Do you use SSD with your T430s @zikezhang?

**Comment by zikezhang** [comment]
I don't use SSD for my T430s.

**Comment by nhutdm** [comment]
Hi @zikezhang, your CPU is OK. I think you should remove TRIM support for SSD on config.plist.
```
<dict>
	<key>Name</key>
	<string>IOAHCIBlockStorage</string>
	<key>Find</key>
	<data>AEFQUExFIFNTRAA=</data>
	<key>Replace</key>
	<data>AAAAAAAAAAAAAAA=</data>
</dict>
```
